version: "3.9"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    env_file: docker.local.env
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    entrypoint: /entrypoint.sh
    volumes:
      - .:/bravo
    ports:
      - "8000:8000"
      - "4000:4000" # porta ptsvd para debug

    depends_on:
      - db
      